language: node_js
node_js:
  - "8"

sudo: false

install:
  - npm install typescript -g
  - npm install ts-node -g
  - npm install tslint -g  
  - npm install
script:
  - npm run lint
  - npm run test

deploy:
  provider: npm
  email: dev@nowcando.com
  api_key: $NPM_TOKEN
  on:
    branch: master